apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: hello-drone
  labels:
    app: hello-drone
    version: {{truncate build.commit 8}}
spec:
  containers:
  - name: app
    image: inge4pres/hello-drone:{{build.tag}}