baseURL = "http://inge.4pr.es/"
title = "INGE4PRES RATIONAL THOUGHTS"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = "inge4pres"
googleAnalytics = "UA-55252403-1"

Paginate = 20
preserveTaxonomyNames = true

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

[params.info]
description = "Growing knowledge one post at a time"
title404 = "Got lost?"

[params.assets]
favicon = "favicon.ico"
#customCSS = [""]
#customJS = [""]
gopher = "gopher.png" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = "inge4pres"
holder = "Francesco Gualazzi"
startYear = "2012"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2 Jan 2006"
listDateFormat = "2 Jan 2006"
archiveDateFormat = "2 Jan 2006"
hideEntryNavigation = false
hideSocialMenu = false
showReadingTime = true
taxonomyCloudShuffle = true

[params.sidebar]
enable = true
sticky = true

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about"]

[params.opengraph.facebook]
admins = ["francesco.inge"] # array of Facebook IDs
appID = "1845367892442473"
pageID = "358809487873346"

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
# titleSeparator = "•"
titleSeparator = "»"

[params.social]
github = "inge4pres"
twitter = "inge4pres"
linkedin = "francescogualazzi"
instagram = "inge4pres"
email = "fgualazzi@gmail.com"
facebook = "inge4pres"

[params.social.config]
platforms = ["github","twitter","linkedin","email","facebook","instagram"]

[taxonomies]
#author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"
post = "/:year/:month/:day/:filename/"

[[menu.main]]
name = "/"
identifier = "root"
url = "/"
weight = -20

[[menu.main]]
name = "/about"
weight = -10
identifier = "about"
url = "/about"

[[menu.main]]
name = "/resume"
weight = -5
identifier = "resume"
url = "/resume"

[blackfriday]
hrefTargetBlank = true

# Language Configuration
defaultContentLanguage = "en"

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
