version: '3'

services:
  drone-server:
    depends_on:
      - gogs
    image: drone/drone:0.8
    ports:
      - 8000:8000
      - 9000
    volumes:
      - drone-server:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=http://docker.for.mac.host.internal:8000
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=http://gogs:3000
      - DRONE_GOGS_SKIP_VERIFY=true
      - DRONE_SECRET="supersecretkeytousewithmydronecontinuousdeliveryinstance"

  drone-agent:
    image: drone/agent:0.8
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET="supersecretkeytousewithmydronecontinuousdeliveryinstance"

  gogs:
    image: gogs/gogs
    volumes:
      - gogs-data:/data
    ports:
      - 3000:3000
      - 22

volumes:
  drone-server:
  gogs-data:
